name: Pack And Deploy Extension

on:
  push:
    branches: [ main ]
    tags:
    - "v*"
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - run: npm run-script lint

  build_chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'src'
          zipFilePath: 'build/chrome.zip'
      - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          # zip file made at the packExtensionDir step
          zipFilePath: 'build/chrome.zip'
          crxFilePath: 'build/chrome.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
      - name: Upload Crx as artifact
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v2
        with:
          name: extension-zips
          path: ./build/chrome.crx
      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            buld/chrome.crx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - run: node ./deploy/firefox.js
      - name: Upload Extension ZIP as artifact
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v2
        with:
          name: extension-zips
          path: ./*.zip
      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            firefox.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
