name: Pack And Deploy Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      WEBSTORE_REFRESH_TOKEN: '${{ secrets.WEBSTORE_REFRESH_TOKEN }}'
      WEBSTORE_EXTENSION_ID: '${{ secrets.WEBSTORE_EXTENSION_ID }}'
      WEBSTORE_CLIENT_SECRET: '${{ secrets.WEBSTORE_CLIENT_SECRET }}'
      WEBSTORE_CLIENT_ID: '${{ secrets.WEBSTORE_CLIENT_ID }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i chrome-webstore-upload archiver
      - run: node ./deploy/chrome.js
      - name: Upload Extension ZIP as artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: chrome.zip